### ISSUE TITLE
FizzyoDevice.cs StreamReader(string) not compatible with UWP

### ISSUE THREAD

**Issue by tenevdev** [Fizzyo/FizzyoFramework-Unity#1]
A Unity build targeting UWP is not possible with the framework because of the way `FizzyoDevice` reads sample data files. It seems the solution is to use [StorageFile.OpenReadAsync()](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.StorageFile]) and [platform dependent compilation](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html). I would normally submit a PR, but not sure what your plans are @gregsaul.

**Comment by gregsaul** [comment]
Hi @tenevdev thank you for the issue report. Let me know if this commit fixes the problem : e2dd0ac0aec1a6f99aeeaad4e3ed9922974ad791 . I've removed test harnesses from the UWP export as this should be a editor only tool and have fixed a few other small bugs. 
Another team is about to take over the framework to continue with improvements and documentation, so it would be good to wait for this to happen and a release build to be pushed to master before any PR happens around this code.

**Comment by tenevdev** [comment]
Yep, this looks good. I'm mostly working on gameplay features for https://github.com/SelfieSticks/TowerBloCF which don't depend much on the Fizzyo framework at the moment.
