### ISSUE TITLE
BreathQuality always set to 4

### ISSUE THREAD

**Issue by TiernanWatson** [Fizzyo/FizzyoFramework-Unity#5]
The ExhalationCompleteEventArgs argument of the OnBreathEnded method always returns that a breath was of full quality when using BreathQuality.  This was happening in one of the games already made, so I created a fresh project with a fresh scene to test this.  Whether I launch through the scene itself or the calibration scene, the issue persists.  It does this even with the tiniest puffs of air I blow into the device.  I'm using Unity 2018.1.2f1.

Test project attached.
[MyFizzyo.zip](https://github.com/Fizzyo/FizzyoFramework-Unity/files/2102179/MyFizzyo.zip)

**Comment by TiernanWatson** [comment]
So I cloned the dev branch and used that version of the framework.  This did not fix this issue.  So I manually set the MaxPressure and MaxBreathLength properties of the BreathRecogniser object, which fixed the issue, but this required that I edited the calibrateScene.cs script so I could get exhaleTime.  However, that file is part of the framework.

**Comment by leestott** [comment]
this should be now fixed in release.Assortment of fixes #6

**Comment by leestott** [comment]
@TiernanWatson Any issue please open a new issue.
