### ISSUE TITLE
Breadth measurement

### ISSUE THREAD

**Issue by leestott** [Fizzyo/FizzyoFramework-Unity#8]
Update breath measurement within the framework based on the new firmware changes. for the over sensitive calibration code is that using the new joystick code, it might be giving joystick values from 0-255 instead of 0-1 and they will need to be re-mapped in the frameworks.

**Comment by SimonDarksideJ** [comment]
This should already be handled as the values are balanced as they are exposed from the Pressure() function. But will check.

FYI, the 255 rage covers

* 0-127 - Negative values
* 128-255 - Positive values

**Comment by leestott** [comment]
Fixed in Nov 2018 update
